# Site settings
title: Able Enrichment Centre
email: ablemath@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Able Enrichment Centre (AEC) is a non-profit, volunteer operated, community
  organization where students enrich their knowledge, operating skills and
  interests in mathematics.
mailaddress: >
  Able Enrichment Centre<br />
  St. John's Ravenscourt<br />
  400 South Drive<br />
  Winnipeg, MB<br />
  R3T 3K5
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ablemath.ca" # the base hostname & protocol for your site
registrationdate: 2023-09-16
classdate: 2023-09-30

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/announcements/page:num/"
