# Site settings
title: Able Enrichment Centre
email: ablemath@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Able Enrichment Centre (AEC) is a non-profit, volunteer operated, community
  organization where students enrich their knowledge, operating skills and
  interests in mathematics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ablemath.ca" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
